name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200
      - name: Publish NuGet
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: Joqds.Zookeeper.Configuration/Joqds.Zookeeper.Configuration.csproj
          PACKAGE_NAME: Joqds.Zookeeper.Configuration
          NUGET_SOURCE: https://api.nuget.org
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
#      - name: publish on version change
#        id: publish_nuget
#        uses: brandedoutcast/publish-nuget@v2
#        with:
#          PROJECT_FILE_PATH: Joqds.Zookeeper.Configuration/Joqds.Zookeeper.Configuration.csproj
#          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
#          INCLUDE_SYMBOLS: true
          
